- pkgs/frontend/app/CreateRole/page.tsx
- pkgs/frontend/app/NewRoleGranted/page.tsx
- pkgs/frontend/app/SendToken/page.tsx
- pkgs/frontend/app/SplitterCreation/page.tsx
- pkgs/frontend/app/page.tsx
- yarn.lock
> button alignment

- pkgs/frontend/app/CreateRole/page.tsx
- pkgs/frontend/app/NewRoleGranted/page.tsx
- pkgs/frontend/app/SendToken/page.tsx
- pkgs/frontend/app/SplitterCreation/page.tsx
- pkgs/frontend/app/page.tsx
- pkgs/frontend/components/CreateRole.tsx
- pkgs/frontend/components/NewRoleGranted.tsx
- pkgs/frontend/components/SendToken.tsx
- pkgs/frontend/components/SplitterCreation.tsx
> Englishization of descriptions

- pkgs/frontend/app/_app.tsx
- pkgs/frontend/app/page.tsx
- pkgs/frontend/utils/chakra-theme.ts
> add extendTheme

- README.md
- pkgs/contract/contracts/SplitCreator.sol
- pkgs/contract/contracts/ens/ethregistrar/IBaseRegistrar.sol
- pkgs/contract/contracts/ens/registry/ENS.sol
- pkgs/contract/contracts/ens/reverseRegistrar/IReverseRegistrar.sol
- pkgs/contract/contracts/ens/reverseRegistrar/ReverseClaimer.sol
- pkgs/contract/contracts/ens/wrapper/IMetadataService.sol
- pkgs/contract/contracts/ens/wrapper/INameWrapper.sol
- pkgs/contract/contracts/ens/wrapper/INameWrapperUpgrade.sol
- pkgs/contract/contracts/metaTx/SampleForwarder.sol
- pkgs/contract/contracts/mock/SampleCreateSubDomain.sol
- pkgs/contract/ignition/modules/FractionToken.ts
- pkgs/contract/ignition/modules/SampleForwarder.ts
- pkgs/contract/ignition/modules/mock/SampleCreateSubDomain.ts
- pkgs/contract/ignition/util/ethers.ts
- pkgs/contract/outputs/contracts-sepolia.json
- pkgs/contract/package.json
- pkgs/contract/tasks/getAllTokenIds.ts
- pkgs/contract/tasks/getBalance.ts
- pkgs/contract/tasks/setSubnodeRecord.ts
- pkgs/contract/tasks/setSubnodeRecordFromContract.ts
以下の点について修正しました。
1. ENSとの結合 (_asignENSSubDomain の実装を行いました。)
2. SampleForwarderコントラクトをデプロイしました。(デプロイ用のスクリプトを追加しました。)
3. 各種スマートコントラクトの機能を検証するためのタスクファイルを追加しました。
4. タスクファイルでサブドメインをミントできるようにしました。
変更箇所多いですが、確認お願いします！！！
> chore: Add contracts and update dependencies

- pkgs/frontend/app/ProjectTop/page.tsx
- pkgs/frontend/app/_app.tsx
- pkgs/frontend/app/page.tsx
- pkgs/frontend/components/HatList.tsx
- pkgs/frontend/components/ProjectInfo.tsx
- pkgs/frontend/components/RoleList.tsx
- pkgs/frontend/utils/chakra-theme.ts
メインページからProjectTopPageに遷移
ProjectTopPageの作成
> ProjectTopPage

- pkgs/frontend/app/providers.tsx
> デフォルトチェーンをsepoliaにしました。

- pkgs/frontend/app/SendToken/page.tsx
- pkgs/frontend/app/page.tsx
- pkgs/frontend/components/Header.tsx
- yarn.lock
> add Header

- docs/puml/class.puml
- docs/puml/sequence.puml
シーケンス図とクラス図を docs/puml に追加しました！
> add: sequence and class pumls

- pkgs/cli/README.md
- pkgs/cli/package.json
- pkgs/cli/scripts/hat.ts
- pkgs/cli/src/commands/function.ts
- pkgs/cli/src/commands/hats.ts
- pkgs/cli/src/index.ts
- pkgs/cli/src/modules/hatsProtocol.ts
- yarn.lock
以下のようなデータが取ってこれます！
```bash
yarn run v1.22.19
$ yarn workspace cli hat:sample
$ npx ts-node ./scripts/hat.ts
{
id: '0x000000a3',
hats: [
{
id: '0x000000a300000000000000000000000000000000000000000000000000000000',
prettyId: '0x000000a3',
status: true,
createdAt: '1724724433',
details: 'ipfs://bafkreifyjxelzs65gj5dkmtsi56cuzg6nuuqtsztdto57v3b7lzijlweqq',
maxSupply: '1',
eligibility: '0x0000000000000000000000000000000000000000',
imageUri: 'ipfs://bafybeihcpbtwywr2owbngvgn2fjqoukh7ahnwo6vcf7ldnvwpzeccgj6se',
toggle: '0x0000000000000000000000000000000000000000',
levelAtLocalTree: 0,
currentSupply: '1'
},
{
id: '0x000000a300010000000000000000000000000000000000000000000000000000',
prettyId: '0x000000a3.0001',
status: true,
createdAt: '1724725575',
details: …
```
> HatIDを指定したらそれに紐づくHatを全て取得してくるサンプルスクリプトを追加しました。

- package.json
- pkgs/cli/src/commands/wallet.ts
- pkgs/cli/src/services/wallet.ts
> issue#117への対応

- pkgs/cli/src/commands/hats.ts
- pkgs/cli/src/modules/hatsProtocol.ts
関連イシュー
- #103 
実装内容
- コマンド
- createHatを追加
- `modules/hatsProtocol.ts`
- リファクタ
> Feat: add createHat command into commands/hats.ts

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
issueとプルリクのテンプレートを追加してみました。
今後、 Copilot Workspaceで作業したときとかに、自動でプルリクの要約してくれたり、レビューしてくれたりと何かと便利だと思うのでテンプレは作っておいた方が良いかもと思いました。
確認お願いします！！
> issueとプルリクのテンプレートを追加してみました。

- pkgs/frontend/app/routes/login.tsx
- pkgs/frontend/app/routes/signup.tsx
- pkgs/frontend/hooks/useWallet.ts
- SmartAccountとEOAウォレットをuseActiveWallet hookで取得できるように共通化
- embed walletを使う場合はSmartAccountになるようにしている
> unify wallet and smart wallet

- pkgs/frontend/hooks/useHats.ts
- pkgs/frontend/hooks/useWallet.ts
sendTransactionだとスマートウォレットとEOA両方の対応ができないので、writeContractにした
close #214 
> use writeContract for useHats

- pkgs/frontend/app/components/Header.tsx
- pkgs/frontend/app/components/StickyNav.tsx
- pkgs/frontend/app/components/icon/WorkspaceIcon.tsx
- pkgs/frontend/app/routes/$treeId.tsx
- pkgs/frontend/app/routes/$treeId_.member.tsx
- pkgs/frontend/app/routes/$treeId_.splits._index.tsx
- pkgs/frontend/app/routes/workspace._index.tsx
- pkgs/frontend/hooks/useENS.ts
- pkgs/frontend/hooks/useHats.ts
> Add sticky nav

- pkgs/frontend/app/routes/$treeId_.assistcredit-history.tsx
- pkgs/frontend/app/routes/$treeId_.member.tsx
- pkgs/frontend/gql/gql.ts
- pkgs/frontend/gql/graphql.ts
- pkgs/frontend/hooks/useFractionToken.ts
- pkgs/frontend/hooks/useWorkspace.ts
- Add endpoint for transaction history of fraction token
- add timestamp and blocknumber to subgraph
- add transaction list page
> Add subgraph for fraction token history

- pkgs/frontend/hooks/useHats.ts
- useHats の getHat 関数を useCallback に
> fix: getHat to useCallback for hats 429 error

- pkgs/frontend/app/routes/$treeId_.$hatId_.assign.tsx
- pkgs/frontend/app/routes/$treeId_.roles_.new.tsx
- pkgs/frontend/app/routes/$treeId_.splits.new.tsx
- pkgs/frontend/app/routes/signup.tsx
- ロール作成後、ロール画面に遷移
- ロールアサイン後、ロール画面に遷移
close #249 
close #250 
close #248 
> Fix redirect after role assign and craete

- pkgs/frontend/app/components/SwitchNetwork.tsx
- pkgs/frontend/app/root.tsx
- pkgs/frontend/hooks/useWallet.ts
Coin base smart walletに接続して使えるように調整
- Privyの設定
- ネットワーク切り替えを設定
close #237 
> Integrate Coinbase Smart Wallet

- pkgs/contract/contracts/splitscreator/SplitsCreator.sol
- 分配先が1アドレスのみの場合、フロントエンドのSDKでエラーが出るかつ一人というのはユースケース上ありえないので、スマコン側でエラーが出るようにした
close #252 
> update splits creator

- biome.json
- pkgs/contract/.openzeppelin/holesky.json
- pkgs/contract/contracts/bigbang/BigBang.sol
- pkgs/contract/contracts/bigbang/mock/BigBang_Mock_v2.sol
- pkgs/contract/contracts/fractiontoken/FractionToken.sol
- pkgs/contract/contracts/fractiontoken/mock/FractionToken_Mock_v2.sol
- pkgs/contract/contracts/splitscreator/SplitsCreatorFactory.sol
- pkgs/contract/contracts/splitscreator/mock/SplitsCreator_Mock_v2.sol
- pkgs/contract/contracts/utils/Create2Deployer.sol
- pkgs/contract/contracts/utils/ProxyAdminTemp.sol
- pkgs/contract/helpers/deploy/BigBang.ts
- pkgs/contract/helpers/deploy/Create2Factory.ts
- pkgs/contract/helpers/deploy/FractionToken.ts
- pkgs/contract/helpers/deploy/Hats.ts
- pkgs/contract/helpers/deploy/Splits.ts
- pkgs/contract/helpers/deploy/Upgradeable.ts
- pkgs/contract/helpers/upgrade/bigbang.ts
- pkgs/contract/helpers/upgrade/fractionToken.ts
- pkgs/contract/helpers/upgrade/splitsCreatorFactory.ts
- pkgs/contract/outputs/contracts-holesky.json
- pkgs/contract/outputs/contracts-sepolia.json
- pkgs/contract/scripts/deploy/create2.ts
- pkgs/contract/test/BigBang.ts
- pkgs/contract/test/FractionToken.ts
- pkgs/contract/test/HatsHatCreatorModule.ts
- pkgs/contract/test/HatsTimeFrameModule.ts
- pkgs/contract/test/IntegrationTest.ts
- pkgs/contract/test/SplitsCreator.ts
- pkgs/frontend/app/root.tsx
- pkgs/subgraph/src/mapping.ts
- 異なるチェーンでも同じコントラクトアドレスでデプロイできるようにCreate2.tsをつくった
close #273 
> Add create2 script

- pkgs/subgraph/config/sepolia.json
> fix subgraph

- pkgs/frontend/app/components/Header.tsx
メニューの一部について、ホバー時のマウスカーソルをポインターにして分かりやすくしてみました
- ワークスペース設定
- ワークスペース一覧
- ログアウト
> chore: add cursor pointer style to menu items in Header component

- lefthook.yaml
- pkgs/frontend/app/routes/workspace.new.tsx
- pkgs/frontend/hooks/useBigBang.ts
ワークスペース作成後のトランザクションハッシュを確認し、イベントログを解析する処理において、`Executed` のログから `topHatId` を取得するロジックが正常に機能していませんでした。
ログを確認したところ、`Executed` が `eventName` として渡されておらず、`parsedLog` が空 (`[]`) の状態になっていました。その結果、後続の `topHatId` から `treeId` を導出するロジックや画面遷移の処理が動作していませんでした。
もしかすると下記課題とは別課題かもしれない・・・・
https://github.com/hackdays-io/toban/issues/245
https://github.com/hackdays-io/toban/issues/255
改修後はtopHatIdの取得および画面遷移共に問題なく機能していることを確認済みです。
https://sepolia.etherscan.io/tx/0x690945a7cb4cc70981653ba73919ab8a968a4c00fbda2ce8f551a17da9c328ac#eventlog
> Update log parsing logic

- README.md
- biome.json
- pkgs/frontend/abi/erc20.ts
- pkgs/frontend/app/components/Header.tsx
- pkgs/frontend/app/routes/$treeId_.settings.tsx
- pkgs/frontend/app/routes/login.tsx
- pkgs/frontend/app/routes/transaction.tsx
トランザクション実行画面を追加しました。
ネイティブトークンとERC20トークンでテスト済みです。USDCでテスト済みです。
Metamaskとsmartwallet(メールアドレスで作ったテスト用アカウント)でテストです。
よろしくお願いします。
Fixes #304 
今、GitHub copilotに作ってもらったサマリーです。
This pull request includes several changes to add new functionality, update existing components, and improve code organization. The most important changes include adding a new transaction page, updating the ERC20 ABI, and modifying the navigation in the header component.
* [`pkgs/frontend/app/routes/transaction.tsx`](diffhunk://#diff-b02f56c74598c6ee6a10a11e941098ffffc0166131052776a2e0d3120e7b1b84R1-R201): Added a new transaction page that allows users to execute ERC20 and native token transactions. This includes handling transaction execution, user input for contract address, recipient, and amount, and displaying …
> Issue/304 対応しました！ トランザクション実行画面を追加しました。

- pkgs/frontend/app/routes/$treeId_.roles_.new.tsx
- pkgs/frontend/app/routes/workspace.new.tsx
- pkgs/frontend/hooks/useIpfs.ts
> fix image error

- pkgs/contract/contracts/bigbang/BigBang.sol
- pkgs/contract/contracts/bigbang/mock/BigBang_Mock_v2.sol
- pkgs/contract/contracts/splitscreator/ISplitsCreator.sol
- pkgs/contract/contracts/splitscreator/ISplitsCreatorFactory.sol
- pkgs/contract/contracts/splitscreator/SplitsCreator.sol
- pkgs/contract/contracts/splitscreator/SplitsCreatorFactory.sol
- pkgs/contract/contracts/thankstoken/IThanksToken.sol
- pkgs/contract/contracts/thankstoken/IThanksTokenFactory.sol
- pkgs/contract/contracts/thankstoken/ThanksToken.sol
- pkgs/contract/contracts/thankstoken/ThanksTokenFactory.sol
- pkgs/contract/helpers/deploy/ThanksToken.ts
- pkgs/contract/test/BigBang.ts
- pkgs/contract/test/IntegrationTest.ts
- pkgs/contract/test/SplitsCreator.ts
- pkgs/contract/test/ThanksToken.ts
RoleShare に加え、ThanksToken でも分配の重みを計算。
その後、かなり変更を加えました。
このPRにThanksTokenのCloneデプロイ化を含んでいます。
Soldityの実装とテスト、完成してます！
> SplitsCreator のロジックに ThanksToken を追加
